# vim: nospell
language: generic
dist: trusty
sudo: required

cache:
  timeout: 600
  directories:
    - $HOME/.stack
    - .stack-work/install

addons:
  apt:
    sources: &apt_sources
      - hvr-ghc
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'

    packages: &apt_packages
      - g++-4.8
      - libgmp-dev
      - happy-1.19.5
      - alex-3.1.7
      - llvm-4.0-dev

matrix:
  fast_finish: true
  include:
    - env: GHC=8.0.2 CABAL=1.24 LLVM=4.0.0 CUDA=8.0.61-1
      compiler: "GHC 8.0"
      addons:
        apt:
          sources: *apt_sources
          packages:
            - *apt_packages
            - cabal-install-1.24

before_install:
  - export PATH=/opt/cabal/$CABAL/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH
  - source .travis/install-cuda-trusty.sh
  - source .travis/install-stack.sh
  - source .travis/update-ghc-settings.sh
  - travis_retry stack install c2hs --fast --no-terminal

install:
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - stack --version
  - cabal --version
  - opt --version; true
  - llc --version; true
  - travis_retry stack build --fast --test --bench --only-dependencies --no-terminal --no-haddock-deps

script:
  - stack build --fast --test --no-run-tests --bench --no-run-benchmarks --no-terminal --haddock --no-haddock-deps
  - stack test --test-arguments="--plain"

