# vim: nospell
language: minimal
dist: trusty
sudo: required  # not really, but travis is broken

cache:
  directories:
    - $HOME/.stack
    - .stack-work/install

addons:
  apt:
    sources: &apt_sources
      - hvr-ghc
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
      - llvm-toolchain-trusty-3.5
      - llvm-toolchain-trusty-3.8
    packages: &apt_packages
      - nvidia-cuda-toolkit
      - g++-4.8
      - libgmp-dev
      - happy-1.19.5
      - alex-3.1.7

matrix:
  fast_finish: true
  include:
    - env: GHC=8.0.2 CABAL=1.24
      compiler: "GHC 8.0"
      addons: { apt: { sources: [ *apt_sources ], packages: [ *apt_packages, cabal-install-1.24 ] }}

before_install:
  - export PATH=/opt/cabal/$CABAL/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH
  - source .travis/install-stack.sh
  - source .travis/update-ghc-settings.sh

install:
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - stack --version
  - cabal --version
  - opt --version; true
  - llc --version; true
  - travis_retry stack build --test --bench --only-dependencies --no-terminal --no-haddock-deps

script:
  - stack build --test --no-run-tests --bench --no-run-benchmarks --no-terminal --haddock --no-haddock-deps
  - stack test

