# For more information, see: http://docs.haskellstack.org/en/stable/yaml_configuration.html
# vim: nospell

resolver: lts-5.11

packages:
- '.'
- location:
    git:    https://github.com/tmcdonell/accelerate.git
    commit: 9d0118f8ef3cd47d64a737b9d7d1d902a5ee72b7
  extra-dep: true

- '../lol/lol'
# - location:
#     git:    https://github.com/tmcdonell/Lol.git
#     commit: 634da1b6fd4b5927239025e4c8bbe64736e297d5
#   extra-dep: true
#   subdirs:
#     - 'lol'

# - '../../numeric-prelude-accelerate'
- location:
    git:    https://github.com/tmcdonell/numeric-prelude-accelerate.git
    commit: a20d0278a8905ce05fd357fdd5594692edddc4e6
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/accelerate-cuda.git
    commit: e5d6dbfcf557fb1dd8eb3f295272fffd19fa3029
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/accelerate-llvm.git
    commit: 20d417aaee1d26f37255929ed604a6d364832bbb
  extra-dep: true
  subdirs:
    - 'accelerate-llvm'
    - 'accelerate-llvm-native'
    - 'accelerate-llvm-ptx'

extra-deps:
- 'arithmoi-0.4.1.3'
- 'chaselev-deque-0.5.0.5'
- 'cuda-0.7.0.0'
- 'exception-mtl-0.4'
- 'language-c-quote-0.11.5.1'
- 'libffi-0.1'
- 'llvm-general-3.5.1.2'
- 'llvm-general-pure-3.5.1.0'
- 'mainland-pretty-0.4.1.3'
- 'non-negative-0.1.1'
- 'numeric-prelude-0.4.2'
- 'storable-record-0.0.3.1'
- 'symbol-0.2.4'
- 'tagged-transformer-0.8'
- 'unique-0'

# held back to satisfy tagged-transformer deps
- 'distributive-0.4.4'
- 'semigroupoids-4.3'

# Override default flag values for local packages and extra-deps
flags:
  lol-accelerate:
    cuda: false
    llvm-cpu: false
    llvm-gpu: false

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
