# For more information, see: http://docs.haskellstack.org/en/stable/yaml_configuration.html
# vim: nospell

resolver: lts-7.0
compiler: ghc-8.0.2

packages:
- '.'

- location:
    git:    https://github.com/AccelerateHS/accelerate.git
    commit: 3fb349fc9fb4ed957ca847941afbe86cb5fa457b
  extra-dep: true

- location:
    git:    https://github.com/AccelerateHS/accelerate-io.git
    commit: f4c84a5c961345bf65059f555f21c6e8bf3070a1
  extra-dep: true

- location:
    git:    https://github.com/AccelerateHS/accelerate-cuda.git
    commit: cd8d31c24717ab1041057d1979113689ac79fead
  extra-dep: true

- location:
    git:    https://github.com/AccelerateHS/accelerate-llvm.git
    commit: 623b04949a873fe15ffa9d10eaf83b992b860f4b
  extra-dep: true
  subdirs:
    - 'accelerate-llvm'
    - 'accelerate-llvm-native'
    - 'accelerate-llvm-ptx'

- location:
    git:    https://github.com/tmcdonell/numeric-prelude-accelerate.git
    commit: 8adc16cf42bfc43ca3967b8bdc33d4d442026751
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/Lol.git
    commit: b42b21eb926c4662964ac3775d688a71f38ccc75
  extra-dep: true
  subdirs:
    - 'lol'
    - 'lol-apps'
    - 'lol-benches'
    - 'lol-cpp'
    - 'lol-repa'
    - 'lol-tests'

- location:
    git:    https://github.com/bscarlet/llvm-general.git
    # commit: 730ceeee3776a1f62bc874ec166d277124a2294b  # 3.5
    commit: 529f9bf117b5ffd1ccf7ebeb679a97b3b1c67938  # 3.8
    # commit: ec1ad5bd2112e7f64dbb43441b5e2075cf6ad8e7  # 3.9
  extra-dep: true
  subdirs:
    - 'llvm-general'
    - 'llvm-general-pure'

extra-deps:
- 'chaselev-deque-0.5.0.5'
- 'cuda-0.7.5.2'
- 'libffi-0.1'
# - 'llvm-general-3.5.1.2'
# - 'llvm-general-pure-3.5.1.0'
- 'non-negative-0.1.1'
- 'numeric-prelude-0.4.2'
- 'tagged-transformer-0.8'
- 'unique-0'

# Override default flag values for local packages and extra-deps
flags:
  llvm-general:
    shared-llvm: true
  lol-accelerate:
    cuda: false
    llvm-cpu: false
    llvm-ptx: false
  accelerate:
    internal-checks: false
    unsafe-checks: false
    bounds-checks: true
    debug: false
    ekg: false
  accelerate-cuda:
    debug: false
  accelerate-llvm-native:
    debug: false
  accelerate-llvm-ptx:
    debug: false
    nvvm:  false

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
