# For more information, see: http://docs.haskellstack.org/en/stable/yaml_configuration.html
# vim: nospell

resolver: lts-9.0

packages:
- '.'

- location:
    git:    https://github.com/tmcdonell/numeric-prelude-accelerate.git
    commit: 330f2d74a8fa135c0ca143d39c53a56f2eee1fc7
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/Lol.git
    commit: 2979119b1767def6acb1069a440051a853167bef
  extra-dep: true
  subdirs:
    - 'lol'
    - 'lol-apps'

extra-deps:
- 'accelerate-1.1.1.0'
- 'accelerate-io-1.0.0.1'
- 'accelerate-llvm-1.1.0.0'
- 'accelerate-llvm-native-1.1.0.1'
- 'accelerate-llvm-ptx-1.1.0.0'
- 'Cabal-2.0.0.2'
- 'cuda-0.8.0.0'
- 'llvm-hs-5.1.0'
- 'llvm-hs-pure-5.1.0'
- 'nvvm-0.8.0.0'
- 'repa-3.4.1.3'
- 'tagged-transformer-0.8'

# Override default flag values for local packages and extra-deps
flags:
  lol-accelerate:
    llvm-cpu: true
    llvm-ptx: true
    with-apps: true
    with-execs: true
  accelerate:
    debug: true
    ekg: true
  accelerate-llvm-native:
    debug: true
  accelerate-llvm-ptx:
    debug: true
    nvvm:  false

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
